language: node_js
node_js:
  - 0.6
  - 0.8
  - 0.10
env:
  global:
    - TEST_3SCALE_APP_ID=4d4b20b9
    - TEST_3SCALE_APP_KEY=ecce202ecc2eb8dc7a499c34a34d5987
    - secure: ju6dVBnQ1P/HPwRPnCfq0iEVLElqurErOAN2HnVCZ6GEHxRDWHxCxo4oepYBcmx6kNP9zNT2mONo7hfI1bzQPuH+aaQwUZXAEOeu1GZrLNUINYplzQtMTl4fV/tGy6Sl/E36n5cCxpdy6zx5tRQdgNK/Y88WYepWRjqtKqnu7tI=
