language: node_js
sudo: false
cache: npm
node_js:
- "0.10"
- "0.12"
- "4"
before_install:
  - npm install -g npm@2
env:
  global:
    - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8