language: node_js
sudo: false
cache: npm
node_js:
- "0.8"
- "0.10"
before_install:
  - npm install -g npm@~1.4.6
env:
  global:
  - TEST_3SCALE_APP_ID=4d4b20b9
  - TEST_3SCALE_APP_KEY=ecce202ecc2eb8dc7a499c34a34d5987
  - secure: B/3oWYZZttrXVM5IFn2evSuWMOQqEOOMol3nEQ2vEDGQ6rdGjpYLFDO/qMDPA8Af6Vt72lOFKkgzivuBp8nSd4S1YRTazilMle4zCJiJxzPs69kRDVXf/Mn8Qr/YrmgVzhblvdNqbKxTGrYyvDziPkliQKtIhqyILm3d6+CqmYw=
